version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - nvm install 22.18.0 
      - nvm use 22.18.0
      - node -v 
      - echo "라이브러리 설치 중..."
      - npm install
  build:
    commands:
      - echo "Vite 빌드 시작..."
      - npm run build
artifacts:
  base-directory: dist
  files:
    - '**/*'